//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Website.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductTBL
    {
        public int Id { get; set; }
        public int BrandId { get; set; }
        public int TypeId { get; set; }
        public string ProductName { get; set; }
        public string productCoverPhoto { get; set; }
        public string Price { get; set; }
        public string Sizes { get; set; }
    
        public virtual BrandTBL ObjBrand { get; set; }
        public virtual TypeTBL ObjType { get; set; }
    }
}
